#ifndef RADIODEFINES_H
#define RADIODEFINES_H

#define RADIO_RCV_MSG_TYPE_GET_CONTAINER_ID 0
#define RADIO_RCV_MSG_TYPE_DELETE_CONTAINER 1
#define RADIO_RCV_MSG_TYPE_MEASUREMENT 2

#define RADIO_SEND_MSG_TYPE_SET_CONTAINER_ID 0
#define RADIO_SEND_MSG_TYPE_POWER_DOWN 1
#define RADIO_SEND_MSG_TYPE_SET_UPDATE_FREQUENCY 2

#endif // RADIODEFINES_H
