#ifndef RADIODEFINES_H
#define RADIODEFINES_H

#define RADIO_RCV_MSG_TYPE_MEASUREMENT 1
#define RADIO_RCV_MSG_TYPE_DELETE_CONTAINER 2

#define RADIO_SEND_MSG_TYPE_SET_UPDATE_FREQUENCY 1
#define RADIO_SEND_MSG_TYPE_POWER_DOWN 2

#endif // RADIODEFINES_H
