#ifndef RADIODEFINES_H
#define RADIODEFINES_H

#define RADIO_RCV_MSG_TYPE_MEASUREMENT 1
#define RADIO_RCV_MSG_TYPE_POWER_DOWN_REQ 2

#define RADIO_SEND_MSG_TYPE_SET_UPDATE_FREQUENCY 1
#define RADIO_SEND_MSG_TYPE_POWER_DOWN_RSP 2

#endif // RADIODEFINES_H
