#ifndef DB_DEFINES_H
#define DB_DEFINES_H

#define AUTHTOKEN_LENGTH 945
#define FIREBASE_REPLY_MAX 4096

#define FIREBASECONFIG_LINE_LENGTH_MAX 200
#define FIREBASECONFIG_VALUE_LENGTH_MAX 150

#define CURRENT_AMOUNT "currentAmount"
#define MAXIMUM_CAPACITY "maximumCapacity"
#define EMPTY_CONTAINER_WEIGHT "emptyContainerWeight"

#define CONTAINER_ID_NOT_EXISTS 0
#define CONTAINER_ID_EXISTS 1

#endif // DB_DEFINES_H
