#ifndef DEFINES_H
#define DEFINES_H

#define AUTHTOKEN_LENGTH 945
#define MAX_CONTAINERS 1000
#define FIREBASE_REPLY_MAX 4096

#define FIREBASECONFIG_LINE_LENGTH_MAX 200
#define FIREBASECONFIG_VALUE_LENGTH_MAX 150

#endif // DEFINES_H
